// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8bvnLOwKtJcIc7-9BCNEoG5Yzla45qEc',
    appId: '1:985716547158:web:715cbe60df030a0444e5f7',
    messagingSenderId: '985716547158',
    projectId: 'qubitarts-6ae59',
    authDomain: 'qubitarts-6ae59.firebaseapp.com',
    storageBucket: 'qubitarts-6ae59.appspot.com',
    measurementId: 'G-12TYXC8394',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZVTWDK9nTnPVEdGU3wg-GNXK13dbk4A',
    appId: '1:985716547158:android:b11fca898164114a44e5f7',
    messagingSenderId: '985716547158',
    projectId: 'qubitarts-6ae59',
    storageBucket: 'qubitarts-6ae59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1iZBuKZQW7mpHJVomG3N4awj9YUZoqaE',
    appId: '1:985716547158:ios:53d6e77a0f1f201e44e5f7',
    messagingSenderId: '985716547158',
    projectId: 'qubitarts-6ae59',
    storageBucket: 'qubitarts-6ae59.appspot.com',
    iosBundleId: 'com.qubitartsmz.qubitarts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1iZBuKZQW7mpHJVomG3N4awj9YUZoqaE',
    appId: '1:985716547158:ios:53d6e77a0f1f201e44e5f7',
    messagingSenderId: '985716547158',
    projectId: 'qubitarts-6ae59',
    storageBucket: 'qubitarts-6ae59.appspot.com',
    iosBundleId: 'com.qubitartsmz.qubitarts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADQ-YtcNH0ODMaNLUon88awZwcsI_0PwU',
    appId: '1:985716547158:web:db2500e567ff9e0044e5f7',
    messagingSenderId: '985716547158',
    projectId: 'qubitarts-6ae59',
    authDomain: 'qubitarts-6ae59.firebaseapp.com',
    storageBucket: 'qubitarts-6ae59.appspot.com',
    measurementId: 'G-8WMDE0L8HB',
  );

}