name: Add Gradle Wrapper (one-time)

on:
  workflow_dispatch:

permissions:
  contents: write    # allows pushing the new files

jobs:
  add-wrapper:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate wrapper files
        run: gradle wrapper --gradle-version 8.7

      - name: Commit wrapper
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add Gradle wrapper"
          file_pattern: |
            gradlew
            gradlew.bat
            gradle/wrapper/*
